name: Unit tests

on:
  pull_request: {}
  push:
    branch:
      - main

jobs:

  test:
    name: Python
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python: [ 3.6, 3.7, 3.8, 3.9, "3.10" ]
        os:  [ macos-latest, ubuntu-20.04, ubuntu-22.04]
        exclude:
          - os: ubuntu-22.04
            python: 3.6
          - os: ubuntu-22.04
            python: 3.7
          - os: ubuntu-22.04
            python: 3.8
          - os: ubuntu-22.04
            python: 3.9

    defaults:
      run:
        shell: bash

    steps:

      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install GDAL for MacOs
        if: matrix.os == 'macos-latest'
        run: |
             brew install gdal

      - name: Install GDAL for Ubuntu 20
        if: matrix.os == 'ubuntu-20.04'
        run: |
            sudo apt-get update
            sudo add-apt-repository ppa:ubuntugis/ppa && sudo apt-get update
            sudo apt-get install gdal-bin
            sudo apt-get install libgdal-dev
            python3 -m pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`

      - name: Install GDAL for Ubuntu 22
        if: matrix.os == 'ubuntu-22.04'
        run: |
            sudo apt-get update
            sudo apt-get install gdal-bin
            sudo apt-get install libgdal-dev
            python3 -m pip install --global-option=build_ext --global-option="-I/usr/include/gdal" GDAL==`gdal-config --version`

      - name: Install Linux packages for Qt5 support
        if: matrix.os == 'ubuntu-20.04'
        run: |
            sudo apt-get update
            sudo apt-get install qt5-default
            sudo apt-get install libxkbcommon-x11-0
            sudo apt-get install libxcb-icccm4
            sudo apt-get install libxcb-image0
            sudo apt-get install libxcb-keysyms1
            sudo apt-get install libxcb-randr0
            sudo apt-get install libxcb-render-util0
            sudo apt-get install libxcb-xinerama0

      - name: Install Linux packages for Qt5 support
        if: matrix.os == 'ubuntu-22.04'
        # qt5-default has been removed
        run: |
            sudo apt-get update
            sudo apt-get install libxcb-xinerama0

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies and local packages
        if: matrix.os == 'ubuntu-20.04'
        run: |
            python3 -m pip install pyqt5
            python3 -m pip install numpy
            python3 -m pip install vtk
            python3 -m pip install pillow

      - name: Install dependencies and local packages, until Kitware releases official VTK wheels for Python 3.10
        if: matrix.os == 'ubuntu-22.04'
        run: |
            python3 -m pip install numpy
            python3 -m pip install https://github.com/pyvista/pyvista-wheels/raw/main/vtk-9.1.0.dev0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
            python3 -m pip install pillow


      - name: Install pip deps
        run: python3 -m pip install -r requirements.txt

      - name: Run fast tests
        working-directory: .
        run: |
            python3 -m pip install pytest
            cd tests
            python3 -m pytest

      - name: Run slow tests with coverage
        if:  github.ref == 'refs/heads/main'
        working-directory: .
        run: |
            python3 -m pip install pytest-cov
            cd tests
            python3 -m pytest --cov=crumbs --cov-report=xml --cov-branch -s -m slow

      - name: Upload coverage to Codecov
        if:  success() && github.ref == 'refs/heads/main' && matrix.os == 'ubuntu-latest'
        uses: codecov/codecov-action@v2
        with:
          working-directory: crumbs
          fail_ci_if_error: true
          flags: tests
          name: codecov-umbrella
          verbose: true
